modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mechanical_component_pie"
version="1.0"
displayName="mechanical_component_pie"
main="com.anthonyhilyard.minearchive.MineArchiveMod"
displayURL="https://modrinth.com/mod/minearchive"
updateJSONURL="https://modrinth.com/mod/minearchive"
logoFile="icon.png"
authors="你说的对，但是本模组是一个机械动力的附属"
description="机械动力x酒狐"

[[mods.mixinConfigs]]
config="mechanical_component_pie.mixins.json"

[[dependencies.mechanical_component_pie]]
modId="forge"
mandatory=true
versionRange="[47.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.mechanical_component_pie]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[modproperties.minearchive]
configuredProviders=[
    "com.anthonyhilyard.minearchive.compat.configured.mechanical_component_pieConfigProvider"
]
